import type { Metadata } from "next";
import StyledComponentsRegistry from './_lib/registry';
import localFont from 'next/font/local'

import "./globals.css";
import ThemeRegistry from "./projects/_components/ThemeRegistry";

const gtPlanar = localFont({
  src: './fonts/GT-Planar-Regular-Trial.woff2',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={gtPlanar.className}>
      <body>
        <ThemeRegistry>     
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </ThemeRegistry>
      </body>
    </html>
  );
}
